defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - wandb_images_logger
  - _self_

# model_checkpoint:
#   dirpath: ${trainer.default_root_dir}/wandb/checkpoints
#   filename: "epoch_{epoch:03d}"
#   monitor: "val_epoch/total_loss"
#   mode: "min"
#   save_last: True
#   auto_insert_metric_name: False
#   save_weights_only: True

#ie try to do pair acc instead of total loss. total loss might be overfitting
model_checkpoint:
  dirpath: ${trainer.default_root_dir}/wandb/checkpoints
  filename: "epoch_{epoch:03d}"
  #monitor: "val_epoch/PAIR_acc/"
  monitor: "val_epoch/paired_loss"
  mode: "min"
  save_last: False
  auto_insert_metric_name: False
  save_weights_only: True

early_stopping:
  #monitor: "val_epoch/PAIR_acc/"
  monitor: "val_epoch/paired_loss"
  patience: 3
  mode: "min"
  divergence_threshold: 2.0
  #stopping_threshold: 0.97 # stop training immediately once the monitored quantity reaches this threshold
