# @package _global_

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/pairs/pc_correct"

data:
  dset_dict:
    proportion_of_data_to_use: 0.05


trainer:
  min_epochs: 1
  max_epochs: 4

test: False
sync: False
optuna_tuning: True
# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    # 'minimize' or 'maximize' the objective
    direction: maximize
    sampler:
      seed: 123

    storage: null
    study_name: null
    n_trials: 20
    n_jobs: 1
    params:
      model.optimizer.lr: interval(1e-6,1e-1)
      batch_size_all: choice(4,8)
      model.optimizer.rho: choice(0.05,0.2,0.1)
      model.optimizer.adaptive: choice(True,False)
      



#"cummax_mean": "cumsum_norm" "cummax_std"

#python train_rwd_model.py experiment=pointnet_all.yaml -m hparams_search=pointnet_one_optuna       